# OOP STAND FOR OBJECT ORIENTED PROGRAMMING

# COMMON TOPIC IN ALL POPUPLAR PROGRAMING LAUNGUAGES(PYTHON,C++,JAVA)

# OOP IS JUST A STYLE/WAY TO WRITE A CODE

# VERY HELPFULL IN CREARTING REAL WORLD SOFTWARE

# WE WILL SEE OTHER ADVANTAGES WHEN WE WILL START LEARNING OOP

# class, object(instance), method

# list class
# list object
# method

l=[1,2,3]
l2=[4,5,6]
l3=['Muhammmad','Ali']
l.append(8)