/*script generated for free with OnlineDataGenerator available at: https://www.onlinedatagenerator.com */
/* Here is the script This is Generated BY: https://www.onlinedatagenerator.com */
/*How to run a file*/
/*SOURCE D:\Backup\Python\Python Projects\Chapter 24_MYSQL\ExportSQL.sql*/

CREATE TABLE MOCKDATA(ID INT,JobTitle VARCHAR(500),EmailAdress VARCHAR(500),FirstNameLastName VARCHAR(500));

INSERT INTO MOCKDATA VALUES(53,'Vodafone','Abbey_Owens1657@nmz0p.us','Abbey Owens');
INSERT INTO MOCKDATA VALUES(59,'CarMax','Brad_Martin2668@iscmr.shop','Brad Martin');
INSERT INTO MOCKDATA VALUES(7,'Zepter','Jayden_Tyler9982@fhuux.net','Jayden Tyler');
INSERT INTO MOCKDATA VALUES(90,'Areon Impex','Mona_Quinn7330@nb44i.store','Mona Quinn');
INSERT INTO MOCKDATA VALUES(83,'Telekom','Julia_Walker1166@xtwt3.site','Julia Walker');
INSERT INTO MOCKDATA VALUES(77,'Comcast','Juliette_Taylor5773@yafr7.solutions','Juliette Taylor');
INSERT INTO MOCKDATA VALUES(6,'Amazon.com','Bart_Carter7204@fhuux.us','Bart Carter');
INSERT INTO MOCKDATA VALUES(53,'Telekom','Wade_Brooks690@1wa8o.com','Wade Brooks');
INSERT INTO MOCKDATA VALUES(67,'Erickson','Chadwick_Myatt2917@hepmv.tech','Chadwick Myatt');
INSERT INTO MOCKDATA VALUES(67,'Comcast','Angelique_Reid2246@c2nyu.host','Angelique Reid');
INSERT INTO MOCKDATA VALUES(51,'BuzzFeed','Brad_Calderwood5212@avn7d.info','Brad Calderwood');
INSERT INTO MOCKDATA VALUES(55,'It Smart Group','Taylor_Emerson8811@jcf8v.press','Taylor Emerson');
INSERT INTO MOCKDATA VALUES(60,'ENEL','Nate_Vangness8595@jcf8v.store','Nate Vangness');
INSERT INTO MOCKDATA VALUES(23,'Carrefour','Alessia_Middleton6298@iaart.mobi','Alessia Middleton');
INSERT INTO MOCKDATA VALUES(68,'Leadertech Consulting','Fred_Clifford5138@yfxpw.media','Fred Clifford');
INSERT INTO MOCKDATA VALUES(12,'Vodafone','Moira_Ross72@cke3u.design','Moira Ross');
INSERT INTO MOCKDATA VALUES(56,'Comodo','Matt_Fowler3177@bqkv0.press','Matt Fowler');
INSERT INTO MOCKDATA VALUES(60,'Biolife Grup','Trisha_Ellwood7321@karnv.edu','Trisha Ellwood');
INSERT INTO MOCKDATA VALUES(54,'Leadertech Consulting','Kurt_Denton1065@bu2lo.ca','Kurt Denton');
INSERT INTO MOCKDATA VALUES(94,'Boeing','Carl_Davies7560@dvqq2.mobi','Carl Davies');

